vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        candidates:
           uri_prefix: /uploads/images
           upload_destination: '%kernel.project_dir%/public/uploads/images'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true


        resumes:
           uri_prefix: /uploads/files
           upload_destination: '%kernel.project_dir%/public/uploads/files'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true