vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        companies:
            uri_prefix: /uploads/logos
            upload_destination: '%kernel.project_dir%/public/uploads/logos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        candidates:
            uri_prefix: /uploads/images
            upload_destination: '%kernel.project_dir%/public/uploads/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        resumes:
            uri_prefix: /uploads/resumes
            upload_destination: '%kernel.project_dir%/public/uploads/resumes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
