vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        companies:
            uri_prefix: /uploads/companies
            upload_destination: '%kernel.project_dir%/public/uploads/companies'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        
        offers:
            uri_prefix: /uploads/offers
            upload_destination: '%kernel.project_dir%/public/uploads/offers'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        candidates:
            uri_prefix: /uploads/candidates
            upload_destination: '%kernel.project_dir%/public/uploads/candidates'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        resumes:
            uri_prefix: /uploads/resumes
            upload_destination: '%kernel.project_dir%/public/uploads/resumes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
