vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        offers:
            uri_prefix: /uploads/candidatePictures/offerPictures
            upload_destination: '%kernel.project_dir%/public/uploads/offerPictures'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        candidates:
           uri_prefix: /uploads/candidatePictures
           upload_destination: '%kernel.project_dir%/public/uploads/candidatePictures'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        resumes:
           uri_prefix: /uploads/candidateResumes
           upload_destination: '%kernel.project_dir%/public/uploads/candidateResumes'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
